add optional team id to create rule group request
coralogix/rules-api-protobuf pull request #18
Opened 2022-11-28 13:24 UTC by daniellelara

allows rule to be created  for a team (specifically in creating a new team) when signed into another team, when implemented, will check if team id exists as a param, and if not, will take as it does now from auth context

2022-11-28 15:37 UTC, deniszo approved these changes

2022-12-07 12:32 UTC, galrose requested changes

2022-12-07 12:32 UTC, galrose commented on com/coralogix/rules/v1/rule_groups_service.proto
> +  optional TeamId team_id = 9;
why not?
```suggestion
  google.protobuf.UInt32Value team_id = 9;
```

2022-12-07 12:32 UTC, galrose commented on com/coralogix/rules/v1/rule_groups_service.proto
> +  optional TeamId team_id = 9;
and you dont need to optional proto3 is optional by default :)

2022-12-07 12:34 UTC, galrose submitted a review, later dismissed

2022-12-07 12:35 UTC, daniellelara commented on com/coralogix/rules/v1/rule_groups_service.proto
> +  optional TeamId team_id = 9;
in other protobuf definitions we have used teamId as a new message type

2022-12-07 12:37 UTC, galrose commented on com/coralogix/rules/v1/rule_groups_service.proto
> +  optional TeamId team_id = 9;
oh I see, well its a personal preference not that important

2022-12-07 12:38 UTC, galrose approved these changes

2022-12-07 12:38 UTC, merged